# Generated by Django 6.1.1 on 2026-09-28 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del usuario.', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico único.', max_length=254, unique=True)),
                ('dni', models.CharField(help_text='Número de documento (7 u 8 dígitos).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$')])),
                ('birth_date', models.DateField(help_text='Fecha de nacimiento.')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('cliente', 'Cliente')], default='cliente', help_text='Rol del usuario.', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
